python: fix echoserver working on Python 2.7.2
Traceback (most recent call last):
  File "echoserver.py", line 51, in <module>
    print "Serving on localhost:%d\n" % (port,)
TypeError: %d format: a number is required, not tuple